### ISSUE TITLE
How can I test the Npgsql.AgensGraph?

### ISSUE THREAD

**Issue by bylee5** [johnberzy-bazinga/Npgsql.AgensGraph#1]
I want to use the Npgsql.AgensGraph.

Can you let me know how can I test the Npgsql.AgensGraph?

thanks.

**Comment by johnberzy-bazinga** [comment]
I've committed a sample showing a simple test case https://github.com/johnberzy-bazinga/Npgsql.AgensGraph/commit/b1a4bef967adc0e868e509f990353f59b8c7e587

What environment are you running? The only dependency is [dotnet core 2.0 SDK](https://www.microsoft.com/net/download/). 

To run the tests you can do that via command line:

`git checkout tests`
`cd Npgsql.AgensGraph.Tests`
`dotnet restore`
`dotnet test`

Thanks,
John

**Comment by bylee5** [comment]
Thanks.
